// Code generated by sqlc. DO NOT EDIT.

package pgsql

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID             sql.NullInt64
	StartTs        time.Time
	EndTs          time.Time
	TotalTimerTime sql.NullInt32
	NumSessions    sql.NullInt32
	Type           sql.NullInt32
	Event          int16
	EventType      int16
	LocalTs        sql.NullTime
	EventGroup     int16
}
