// Code generated by sqlc. DO NOT EDIT.

package pgsql

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID             sql.NullInt64
	StartTs        time.Time
	EndTs          time.Time
	TotalTimerTime sql.NullFloat64
	NumSessions    sql.NullInt32
	Type           sql.NullInt32
	Event          int16
	EventType      int16
	LocalTs        sql.NullTime
	EventGroup     int16
}

type Monitoring struct {
	ID              sql.NullInt64
	Ts              time.Time
	Cycles          sql.NullInt32
	Calories        int16
	Distance        sql.NullFloat64
	ActiveTime      sql.NullFloat64
	ActivityType    int16
	ActivitySubType int16
	LocalTs         sql.NullTime
}

type MonitoringsDaily struct {
	Day          interface{}
	Max          interface{}
	ActivityType int16
}

type Record struct {
	ID       int64
	Distance sql.NullInt32
	Time     sql.NullInt32
}

type Session struct {
	ID               sql.NullInt64
	StartTs          time.Time
	EndTs            time.Time
	Event            int16
	EventType        int16
	Sport            int16
	SubSport         int16
	TotalElapsedTime sql.NullFloat64
	TotalTimerTime   sql.NullFloat64
	TotalDistance    sql.NullFloat64
	TotalCalories    int16
	AvgSpeed         sql.NullFloat64
	MaxSpeed         sql.NullFloat64
	AvgHeartRate     int16
	MaxHeartRate     int16
}
