// Code generated by sqlc. DO NOT EDIT.

package pgsql

import (
	"database/sql"
)

type Activity struct {
	ID             int64
	Ts             sql.NullTime
	TotalTimerTime sql.NullInt32
	NumSessions    sql.NullInt32
	Type           sql.NullInt32
	Event          sql.NullInt32
	EventType      sql.NullInt32
	LocalTs        sql.NullTime
	EventGroup     sql.NullInt32
}
