// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package pgsql

import (
	"context"
	"database/sql"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (ts, total_timer_time, num_sessions, type, event, event_type, local_ts, event_group)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id, ts, total_timer_time, num_sessions, type, event, event_type, local_ts, event_group
`

type CreateActivityParams struct {
	Ts             sql.NullTime
	TotalTimerTime sql.NullInt32
	NumSessions    sql.NullInt32
	Type           sql.NullInt32
	Event          sql.NullInt32
	EventType      sql.NullInt32
	LocalTs        sql.NullTime
	EventGroup     sql.NullInt32
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.Ts,
		arg.TotalTimerTime,
		arg.NumSessions,
		arg.Type,
		arg.Event,
		arg.EventType,
		arg.LocalTs,
		arg.EventGroup,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.TotalTimerTime,
		&i.NumSessions,
		&i.Type,
		&i.Event,
		&i.EventType,
		&i.LocalTs,
		&i.EventGroup,
	)
	return i, err
}
