// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package pgsql

import (
	"context"
	"database/sql"
	"time"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (
    start_ts,
    end_ts,
    total_timer_time,
    num_sessions,
    type,
    event,
    event_type,
    local_ts,
    event_group
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT DO NOTHING
RETURNING id, start_ts, end_ts, total_timer_time, num_sessions, type, event, event_type, local_ts, event_group
`

type CreateActivityParams struct {
	StartTs        time.Time
	EndTs          time.Time
	TotalTimerTime sql.NullInt32
	NumSessions    sql.NullInt32
	Type           sql.NullInt32
	Event          int16
	EventType      int16
	LocalTs        sql.NullTime
	EventGroup     int16
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.StartTs,
		arg.EndTs,
		arg.TotalTimerTime,
		arg.NumSessions,
		arg.Type,
		arg.Event,
		arg.EventType,
		arg.LocalTs,
		arg.EventGroup,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.StartTs,
		&i.EndTs,
		&i.TotalTimerTime,
		&i.NumSessions,
		&i.Type,
		&i.Event,
		&i.EventType,
		&i.LocalTs,
		&i.EventGroup,
	)
	return i, err
}
